### ISSUE TITLE
karnaugh map editor: KNF schematic representation wrong

### ISSUE THREAD

**Issue by drtrigon** [laszlokorte/tams-tools#3]
The schematic representation of the KNF expression is wrong. The inputs are connected in inverted manner to what is correct. The algebraic/boolean expression is correct. Can you please fix this? Thanks!

**Comment by laszlokorte** [comment]
Thank you very much for reporting this! Should be fixed now.

**Comment by drtrigon** [comment]
Thanks! Is this online on https://tams.informatik.uni-hamburg.de/research/software/tams-tools/kvd-editor.html? I'm asking because it is still wrong.

Example:
![grafik](https://user-images.githubusercontent.com/18975831/68245024-6a3ec300-0016-11ea-9f2a-e0096e05e814.png)
The green group schould be connected to the "NOT C" port instead of the "C" port. (In the green group C=1 but the output should be 0 and thus connected to the "NOT C".)

**Comment by laszlokorte** [comment]
The latest (fixed) version is online here: https://thesis.laszlokorte.de/demo/kvd-editor.html

But I will ask the responsible to update the tams.informatik.uni-hamburg.de version as well.

**Comment by drtrigon** [comment]
The uni-hamburg version is up-to-date now. Thanks! Also thanks for the other link!

Now the **schematic is correct** but **the algebraic/boolean expression is not**. For the example mentioned it states now: O1=((¬B ∨ ¬C) ∧ (C)) which is wrong. Before the fix this was correct. The problem that the algebraic/boolean expression output does not agree with the schematic output still exists, the two have swapped only.

**Comment by laszlokorte** [comment]
Good catch! Thanks! Now it should work correctly. Please take another look at https://thesis.laszlokorte.de/demo/kvd-editor.html

**Comment by drtrigon** [comment]
Yes, looks better now - should be fine! Thanks and greetings!
